### ISSUE TITLE
Allowing for direct pasting of images into the text editor

### ISSUE THREAD

**Issue by zuron7** [shridarpatil/frappe_tinymce#3]
** The Problem **
In the quill text editor that is available by default in Frappe, it's quite easy to paste images, one can take a screenshot on Windows with the Win + Shift + S shortcut and then go over to the editor and Ctrl + V and the image is there.

In the tinyMCE editor, when we typically try the same behaviour as above, the image does not auto-paste. 

** What I've tried **
- Headed over to the tinyMCE website, tiny.cloud and checked whether it was a limitation on the editor side. Tried pasting an image into their online editor. Works without any problems. 

** Solutions **
- To be discussed.

**Comment by shridarpatil** [comment]
@zuron7 looks like some issue, I tried, and it doesn't work for me either.

**Comment by shridarpatil** [comment]
This is fixed 
![screenshot](https://user-images.githubusercontent.com/11792643/197688505-7937fba8-4853-43f8-affd-013eb7b865bc.gif)
